---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saleor-core.fullname" . }}-plugins
  labels:
    {{- include "saleor-core.labels" . | nindent 4 }}
data:
  configure_plugins.sh: |
{{ .Files.Get "config/configure_plugins.sh" | indent 4 }}
