---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saleor-core.fullname" . }}-backup
  labels:
    {{- include "saleor-core.labels" . | nindent 4 }}
data:
  backup.sh: |
{{ .Files.Get "config/backup.sh" | indent 4 }}
