{{- $topLevelScope := . }}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "saleor-core.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "saleor-core.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          # Path for api
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-api
                port:
                  number: {{ $svcPort }}
          # Paths for web serving /media and /static
          {{- if not $topLevelScope.Values.externalServices.cloudStorage.enabled }}
          - path: {{ . }}{{ trimPrefix "/" $topLevelScope.Values.staticUrl }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-web
                port:
                  number: 8080
          - path: {{ . }}{{ trimPrefix "/" $topLevelScope.Values.mediaUrl }}
            pathType: Prefix
            backend:
              service:
                name:  {{ $fullName }}-web
                port:
                  number: {{ $svcPort }}
          {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
