{{- if and .Values.persistence.enabled (not .Values.persistence.existingPvc) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "saleor-core.fullname" . }}
  labels:
    {{- include "saleor-core.labels" . | nindent 4 }}
spec:
{{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  volumeMode: {{ .Values.persistence.volumeMode }}
{{- end -}}
