apiVersion: v1
kind: Service
metadata:
  name: {{ include "saleor-core.fullname" . }}-api
  labels:
    {{- include "saleor-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.gunicorn.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "saleor-core.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
