{{- if not .Values.externalServices.cloudStorage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "saleor-core.fullname" . }}-web
  labels:
    {{- include "saleor-core.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.web.port }}
      protocol: TCP
      name: http
    - port: {{ int .Values.service.port | add1 }}
      targetPort: {{ int .Values.web.port | add1 }}
      protocol: TCP
      name: healthcheck
  selector:
    {{- include "saleor-core.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}