{{- $thisJob := .Values.jobs.init.plugins }}
{{- if $thisJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: 0{{ $thisJob.weight }}-{{ include "saleor-core.fullname" . }}-plugins
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": {{ $thisJob.weight | quote }}
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  activeDeadlineSeconds: {{ default 300 $thisJob.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ default 600 $thisJob.ttlSecondsAfterFinished }}
  backoffLimit: {{ default 5 $thisJob.backOffLimit }}
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: 0{{ $thisJob.weight }}-{{ include "saleor-core.fullname" . }}-plugins
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "saleor-core.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        # ConfigMap for the nginx configuration and the static assets script
        - name: configure-plugins
          configMap:
            name: {{ include "saleor-core.fullname" . }}-plugins
      restartPolicy: OnFailure
      initContainers:
        # Wait for successful response from postgresql
        - name: "{{- include "saleor-core.jobContainerName" . }}-plugins-init-1"
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- include "saleor-core.env" . | indent 10 }}
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag | default (cat "dev-" .Chart.AppVersion) | nospace }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - >
              {{ include "saleor.postgresql.isReady" . | nindent 14 }}
      containers:
        - name: "{{- include "saleor-core.jobContainerName" . }}-plugins"
      containers:
        - name: "{{- include "saleor-core.jobContainerName" . }}-plugins"
          volumeMounts:
            - name: configure-plugins
              mountPath: /home/saleor/configure_plugins.sh
              subPath: configure_plugins.sh
              readOnly: true
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- include "saleor-core.env" . | indent 10 }}
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag | default (cat "dev-" .Chart.AppVersion) | nospace }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - /home/saleor/configure_plugins.sh
          args:
            - '$(POSTGRESQL_PASSWORD)'
            - '$(POSTGRESQL_HOST)'
            - '$(POSTGRESQL_PORT)'
            - '$(POSTGRESQL_USER)'
            - '$(POSTGRESQL_DATABASE)'
            - '$(VATLAYER_API_KEY)'
            - '$(BRAINTREE_PRIVATE_KEY)'
            - '$(BRAINTREE_PUBLIC_KEY)'
            - '$(BRAINTREE_SANDBOX_MODE)'
            - '$(BRAINTREE_MERCHANT_ID)'
            - '$(BRAINTREE_CURRENCIES)'
            - '$(BRAINTREE_REQUIRE_3D_SECURE)'
{{- end }}
